apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver-canary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webserver
      track: canary
  template:
    metadata:
      labels:
        app: webserver
        track: canary
    spec:
      containers:
      - image: nginx
        name: nginx
